apiVersion: v1
kind: BuildConfig
metadata:
  name: mypipeline
  labels:
    name: mypipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "myapp", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      #      jenkinsfile: "node('maven') {\nstage 'build'\nopenshiftBuild(buildConfig: 'myphp', showBuildLogs: 'true')\nstage 'deploy'\nopenshiftDeploy(deploymentConfig: 'myphp')\nopenshiftScale(deploymentConfig: 'myphp',replicaCount: '2')\n}"
      jenkinsfile: |-
        node('maven') {
          stage 'build'
            openshiftBuild(buildConfig: 'myapp', showBuildLogs: 'true')
          stage 'deploy'
            openshiftDeploy(deploymentConfig: 'myapp')
            openshiftScale(deploymentConfig: 'myapp',replicaCount: '2')
        }
  output:
  resources:
  postCommit:
